ALTER TABLE ads ADD COLUMN IF NOT EXISTS impressions INTEGER NOT NULL DEFAULT 0;
ALTER TABLE ads ADD COLUMN IF NOT EXISTS clicks INTEGER NOT NULL DEFAULT 0;

INSERT INTO site_settings (key, value) VALUES ('ads_auto_publish', 'false')
ON CONFLICT (key) DO NOTHING;
